### PR TITLE
Fix time issue for Fischer/Game modes when using clockside = right.

### PR DESCRIPTION
**Pull request by RandyR99**
Hi Dirk. I think I fixed the time issue mentioned by Wilhelm and Jacek [here](https://groups.google.com/g/picochess/c/ifop9eF_Pv8/m/WnkTSRhyBAAJ). I should have tested better. :^)

### CODE REVIEW

**Comment by RandyR99** [comment]
I forgot to mention that pi.py was the fix for the timing issue. The changes in hw.py relate to using the clock cable and you place the clock on the right side of the board (which I can't do since my cable isn't long enough). I doubt many people use this setup anyway.

Randy

**Comment by tosca07** [comment]
Thank you so much Randy. Really great news. I will check & test with my Rev2 (Wilhelm and you obviously tested the other configurations) once I am back from Lofoten and Senja island in Norway ;-) (in a few days)
Dirk

**Comment by RandyR99** [comment]
Looks like a beautiful place, Dirk. Enjoy your remaining time.

Randy

**Comment by tosca07** [comment]
I still have to check rhis with revelation II (wegen I am back) but the dgt3000 emulation is very accurate so think it is ok ;-)

**Pull request merged**
