### PR TITLE
Compatibility with python-chess 0.25.1

### PR DESCRIPTION
**Pull request by djdekker**
Changes suggested by Jürgen in https://groups.google.com/forum/#!topic/picochess/sHBwvs0A9XM

### CODE REVIEW

**Comment by ScallyBag** [comment]
Hi DJ & Dirk,

I just copied these changes to my system and ran update requirements changing python-chess to 0.25.1 but I’m still getting the error message on the web server

fe383789-ef38-42a9-af31-835f175f65ae

Al.

**Comment by djdekker** [comment]
Hi Al,

The web server is working fine here.

Instead of cloning the jromang repository and manually copying over the modified files from tosca07, I simply cloned the tosca07 fork. Then I applied the two corrections suggested by Jürgen and updated requirements.txt (python-chess = 0.25.1). I'm not getting any error messages on the clock or the web server.

Did you make any other changes to the code?

Greetings,
DJ

**Comment by ScallyBag** [comment]
Hi DJ,

Thanks for the reply. I am meticulous in my copying, I run diff against every file.

However I cloned Dirks repository and ran his requirements, all ok. I then applied your 2 changes of Jürgens, again ok. As soon as I changed python-chess 0.22.1 to 0.25.1 and run requirements I get the error on the web server. Dirk has had the same problems in the past, which is why we went back to 0.22.1

I can’t think what else it might be?

Al.

**Comment by djdekker** [comment]
Hi Al,

Does the log file provide you with any clues?

Could it be that you're experiencing a network issue, like a problem with a firewall or with a VPN connection?

Greetings,
DJ

**Comment by ScallyBag** [comment]
Hi DJ,

I don’t use a VPN. I’ve tried on my iPad my iPhone and my smart TV, I get the same error on the web server. I turned debug on and can see these messages. Note that as soon as I switch back to 
python-chess==0.22.1  no errors are received:

2019-02-18 13:42:07.635   ERROR        web - log_exception: Uncaught exception GET /info?action=get_headers (192.168.1.100)
HTTPServerRequest(protocol='http', host='192.168.1.36', method='GET', uri='/info?action=get_headers', version='HTTP/1.1', remote_ip='192.168.1.100', headers={'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1', 'Referer': 'http://192.168.1.36/', 'If-None-Match': '"3a948daa22ae066dc4833dd843f0c57fd2641ec3"', 'Accept-Encoding': 'gzip, deflate', 'X-Requested-With': 'XMLHttpRequest', 'Connection': 'keep-alive', 'Accept-Language': 'en-gb', 'Accept': '*/*', 'Host': '192.168.1.36'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/picochess/server.py", line 149, in get
    self.write(self.shared['headers'])
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 713, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2019-02-18 13:42:07.652   ERROR        web - log_request: 500 GET /info?action=get_headers (192.168.1.100) 18.73ms
2019-02-18 13:42:07.657    INFO        web - log_request: 200 GET /info?action=get_ip_info (192.168.1.100) 2.91ms
2019-02-18 13:42:07.661    INFO        web - log_request: 304 GET /info?action=get_clock_text (192.168.1.100) 1.57ms
2019-02-18 13:42:15.357   ERROR        web - log_exception: Uncaught exception GET /info?action=get_headers (192.168.1.100)
HTTPServerRequest(protocol='http', host='192.168.1.36', method='GET', uri='/info?action=get_headers', version='HTTP/1.1', remote_ip='192.168.1.100', headers={'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1', 'Referer': 'http://192.168.1.36/', 'Accept-Encoding': 'gzip, deflate', 'X-Requested-With': 'XMLHttpRequest', 'Connection': 'keep-alive', 'Accept-Language': 'en-gb', 'Accept': '*/*', 'Host': '192.168.1.36'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/picochess/server.py", line 149, in get
    self.write(self.shared['headers'])
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 713, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2019-02-18 13:42:15.360   ERROR        web - log_request: 500 GET /info?action=get_headers (192.168.1.100) 3.36ms

Al.

**Comment by djdekker** [comment]
Hi Al,

Does the error disappear if you update requirements.txt like I did in commit 088a516? I found that ConfigArgParse, Flask, paramiko, pyOpenSSL and requests can be updated. I also found that updating tornado to v5.1.1 breaks the web server, so I left that at v4.5.1.

Greetings,
DJ

**Comment by djdekker** [comment]
Hi Al,

Now I'm seeing the 'error' message on the web server, too – but only in the Chromium browser on my RPi or in Chrome on my Mac.

Somewhat surprisingly, there is no error message in Safari 12 on my Mac. Could this different behaviour of web browsers be a clue that may help solve the riddle?

Greetings,
DJ

**Comment by ScallyBag** [comment]
Hi DJ,

Some of my versions were in between Dirks and yours (taken from Jürgen’s requirements on v0.9s)
So I’ve now copied your 
https://github.com/tosca07/picochess/commit/088a51608e4cd2f9f16bc6144a0afc16dcccdf7f commit, which works a treat. 

As soon as change python-chess from 0.22.1 to 0.25.1 it gives an error on my web server, so I’m staying with 0.22.1

Thanks for your efforts,

Al.

**Comment by LocutusOfPenguin** [comment]
DJ:
tornado 5 doesnt work. Thats an old problem.

AL:
GRRR
(taken from Jürgen’s requirements on v0.9s)
0.9S is s=secret, ha.

**Comment by tosca07** [comment]
Thank you all for your suggestions/comments and sorry DJ that I just have seen your request so late.

It is not only the Webserver which causes problems.

My first tests showed that eg reading a position also is no longer working and during longer game play I also had some issues.

So I think until we have the time and ambition to search for all these changes we will have to stick with python-chess 22.1.

But thanks anyway
Dirk

**Pull request closed without merging**
